// One npm package owns all engines. Plugin hosts copy subdirectories independently, so each
// plugin ships an identical, reproducible runtime tarball built from the root manifest/lockfile.
import { readFileSync, writeFileSync, mkdirSync, copyFileSync, readdirSync, mkdtempSync, rmSync, existsSync, statSync } from 'node:fs';
import { resolve, dirname, join } from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const stage = mkdtempSync(join(tmpdir(), 'plainwright-package-'));
// The session pane mod (mods/session-pane/hooks/) ships in every plugin without its tests, with a config naming it.
const MOD = join(root, 'mods/session-pane/hooks');
function copyMod(plugin, name) {
  const target = join(plugin, 'hooks');
  rmSync(target, { recursive: true, force: true });
  for (const file of readdirSync(MOD, { recursive: true })) {
    const from = join(MOD, file);
    if (statSync(from).isDirectory() || file.endsWith('.test.ts')) continue;
    mkdirSync(dirname(join(target, file)), { recursive: true });
    copyFileSync(from, join(target, file));
  }
  const engine = name === 'plainwright' ? 'browser' : 'native';
  writeFileSync(join(target, 'session-pane/config.ts'), '// Generated by scripts/build-plugins.mjs from mods/session-pane/: do not edit.\n' +
    `export const PLUGIN: string = ${JSON.stringify(name)};\nexport const ENGINE: 'browser' | 'native' = ${JSON.stringify(engine)};\n`);
}
try {
  const packageDir = join(stage, 'package');
  mkdirSync(join(packageDir, 'dist'), { recursive: true });
  mkdirSync(join(packageDir, 'bin'));
  copyFileSync(join(root, 'package.json'), join(packageDir, 'package.json'));
  // npm installs honor a published shrinkwrap (package-lock.json alone is ignored in packages).
  copyFileSync(join(root, 'package-lock.json'), join(packageDir, 'npm-shrinkwrap.json'));
  copyFileSync(join(root, 'LICENSE'), join(packageDir, 'LICENSE'));
  // Recursive: dist/ has subfolders (dist/reporters/); a root-only copy shipped a runtime that could not start.
  const shipped = readdirSync(join(root, 'dist'), { recursive: true }).filter((name) => name.endsWith('.js') && !name.endsWith('.test.js')).sort();
  for (const name of shipped) {
    mkdirSync(dirname(join(packageDir, 'dist', name)), { recursive: true });
    copyFileSync(join(root, 'dist', name), join(packageDir, 'dist', name));
  }
  // Every relative import in the shipped runtime must resolve inside the package, to a file: Node ESM does not
  // resolve a bare folder import to its index.js.
  const isFile = (path) => existsSync(path) && statSync(path).isFile();
  const missing = shipped.flatMap((name) => {
    const file = join(packageDir, 'dist', name);
    return [...readFileSync(file, 'utf8').matchAll(/(?:from\s+|import\s*\(\s*|import\s+)['"](\.{1,2}\/[^'"]+)['"]/g)]
      .map((match) => match[1]).filter((spec) => !isFile(resolve(dirname(file), spec))).map((spec) => `dist/${name} -> ${spec}`);
  });
  if (missing.length) throw new Error(`runtime has unresolved imports:\n${missing.join('\n')}`);
  for (const name of ['plainwright.mjs', 'plainwright-computer.mjs', 'plainwright-mobile.mjs']) copyFileSync(join(root, 'bin', name), join(packageDir, 'bin', name));
  const packed = spawnSync(process.platform === 'win32' ? 'npm.cmd' : 'npm',
    ['pack', '--ignore-scripts', '--json', '--pack-destination', stage],
    { cwd: packageDir, encoding: 'utf8', shell: process.platform === 'win32', env: { ...process.env, npm_config_cache: join(stage, 'npm-cache') } });
  if (packed.status !== 0) throw new Error(`npm pack failed: ${packed.stderr || packed.error}`);
  const archive = join(stage, JSON.parse(packed.stdout)[0].filename);
  for (const name of ['plainwright', 'plainwright-computer', 'plainwright-mobile']) {
    const plugin = join(root, 'plugins', name);
    mkdirSync(join(plugin, 'bin'), { recursive: true });
    copyFileSync(archive, join(plugin, 'runtime.tgz'));
    copyFileSync(join(root, 'scripts/plugin-launcher.mjs'), join(plugin, 'bin/launch.mjs'));
    copyFileSync(join(root, 'LICENSE'), join(plugin, 'LICENSE'));
    copyMod(plugin, name);
  }
} finally { rmSync(stage, { recursive: true, force: true }); }
