// The three plugins run the published npm package through npx, pinned to the root package.json version. This
// script writes what each plugin derives from the root: the MCP configs, the npx shim (scripts/plugin-npx.mjs as
// bin/npx.mjs), the version in its three manifests and in the `plainwright@<version>` commands of its skill, the
// license and the session pane mod. Plugin hosts refresh a cached plugin when its version changes, so a new
// runtime version is also a new plugin version.
import { readFileSync, writeFileSync, mkdirSync, copyFileSync, readdirSync, rmSync, statSync } from 'node:fs';
import { resolve, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const { name: PACKAGE, version } = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
// Each plugin's MCP server: the package bin it runs and the arguments after it.
const SERVERS = {
  plainwright: { bin: 'plainwright', args: ['--headless', 'mcp'] },
  'plainwright-computer': { bin: 'plainwright-computer', args: ['mcp'] },
  'plainwright-mobile': { bin: 'plainwright-mobile', args: ['mcp'] },
};
const SEMVER = String.raw`\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?`;
// Hosts start `node` on every platform; the shim starts npx (through cmd /c on Windows).
const SHIM = 'bin/npx.mjs';
const writeJson = (file, value) => writeFileSync(file, JSON.stringify(value, null, 2) + '\n');
const readJson = (file) => JSON.parse(readFileSync(file, 'utf8'));

/** `npx -y --package=plainwright@<version> <bin> ...`: one form for all bins, so a test can swap the package spec. */
export function npxArgs(name, spec = `${PACKAGE}@${version}`) {
  const { bin, args } = SERVERS[name];
  return ['-y', `--package=${spec}`, bin, ...args];
}

// The session pane mod (mods/session-pane/hooks/) ships in every plugin without its tests, with a config naming it.
const MOD = join(root, 'mods/session-pane/hooks');
function copyMod(plugin, name) {
  const target = join(plugin, 'hooks');
  rmSync(target, { recursive: true, force: true });
  for (const file of readdirSync(MOD, { recursive: true })) {
    const from = join(MOD, file);
    if (statSync(from).isDirectory() || file.endsWith('.test.ts')) continue;
    mkdirSync(dirname(join(target, file)), { recursive: true });
    copyFileSync(from, join(target, file));
  }
  const engine = name === 'plainwright' ? 'browser' : 'native';
  writeFileSync(join(target, 'session-pane/config.ts'), '// Generated by scripts/build-plugins.mjs from mods/session-pane/: do not edit.\n' +
    `export const PLUGIN: string = ${JSON.stringify(name)};\nexport const ENGINE: 'browser' | 'native' = ${JSON.stringify(engine)};\n`);
}

function pinSkill(dir) {
  for (const file of readdirSync(dir, { recursive: true })) {
    const path = join(dir, file);
    if (!file.endsWith('.md') || statSync(path).isDirectory()) continue;
    const text = readFileSync(path, 'utf8');
    const pinned = text.replace(new RegExp(`\\b${PACKAGE}@${SEMVER}`, 'g'), `${PACKAGE}@${version}`);
    if (pinned !== text) writeFileSync(path, pinned);
  }
}

function buildPlugin(name) {
  const plugin = join(root, 'plugins', name);
  for (const manifest of ['plugin.json', '.claude-plugin/plugin.json', '.codex-plugin/plugin.json']) {
    writeJson(join(plugin, manifest), { ...readJson(join(plugin, manifest)), version });
  }
  const args = npxArgs(name);
  writeJson(join(plugin, 'mcp.json'), { $schema: 'https://agent-plugins.org/schemas/1.0.0/mcp.schema.json',
    mcpServers: { [name]: { type: 'stdio', command: 'node', args: [SHIM, ...args], cwd: '${PLUGIN_ROOT}' } } });
  writeJson(join(plugin, '.mcp.json'), { mcpServers: { [name]: { command: 'node', args: [`\${CLAUDE_PLUGIN_ROOT}/${SHIM}`, ...args] } } });
  mkdirSync(join(plugin, 'bin'), { recursive: true });
  copyFileSync(join(root, 'scripts/plugin-npx.mjs'), join(plugin, SHIM));
  pinSkill(join(plugin, 'skills'));
  copyFileSync(join(root, 'LICENSE'), join(plugin, 'LICENSE'));
  copyMod(plugin, name);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) for (const name of Object.keys(SERVERS)) buildPlugin(name);
